# Generated by Django 2.0.6 on 2019-05-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='leetcodeUrl',
            new_name='leetcode_url',
        ),
    ]
